from typing import Iterable
import numpy as np

TICKS_PER_SECOND: int

class NativeCore:
    @staticmethod
    def constant(value: float) -> NativeCore: ...
    @staticmethod
    def gaussian(width: float) -> NativeCore: ...
    @staticmethod
    def cos(angular_frequency: float, phase: float = ...) -> NativeCore: ...
    @staticmethod
    def sin(angular_frequency: float, phase: float = ...) -> NativeCore: ...
    @staticmethod
    def square(width: float) -> NativeCore: ...
    @classmethod
    def from_bytes(cls, data: bytes | bytearray | memoryview) -> NativeCore: ...
    def to_bytes(self) -> bytes: ...
    def add_affine(self, other: NativeCore, left_delay: int = ...,
                   left_scale: float = ..., right_delay: int = ...,
                   right_scale: float = ...) -> NativeCore: ...
    def mul_affine(self, other: NativeCore, left_delay: int = ...,
                   left_scale: float = ..., right_delay: int = ...,
                   right_scale: float = ...) -> NativeCore: ...
    def materialize(self, delay: int = ..., scale: float = ...) -> NativeCore: ...
    def evaluate(self, positions: np.ndarray, delay: int = ...,
                 scale: float = ..., lower: float = ...,
                 upper: float = ..., out: np.ndarray | None = ...) -> np.ndarray: ...
    def sample(self, start_tick: int, count: int, step_numerator: int,
               step_denominator: int = ..., delay: int = ...,
               scale: float = ..., lower: float = ..., upper: float = ...,
               bits: int = ..., full_scale: float = ...,
               out: np.ndarray | None = ...) -> np.ndarray: ...
    lower_tick: int
    upper_tick: int
    node_count: int
    hash64: int

class NativeStackCore:
    @classmethod
    def from_events(cls, templates: Iterable[NativeCore], template_ids,
                    delays, scales) -> NativeStackCore: ...
    @classmethod
    def from_bytes(cls, data: bytes | bytearray | memoryview) -> NativeStackCore: ...
    def to_bytes(self) -> bytes: ...
    def evaluate(self, positions: np.ndarray, shift: int = ...,
                 offset: float = ..., out: np.ndarray | None = ...) -> np.ndarray: ...
    def sample(self, start_tick: int, count: int, step_numerator: int,
               step_denominator: int = ..., shift: int = ...,
               offset: float = ..., bits: int = ...,
               full_scale: float = ...,
               out: np.ndarray | None = ...) -> np.ndarray: ...
    def simplify(self, shift: int = ..., offset: float = ...) -> NativeCore: ...
    def materialize(self, shift: int = ...,
                    offset: float = ...) -> NativeStackCore: ...
    event_count: int
    template_count: int
    hash64: int

def native_format_description() -> str: ...
