from typing import Iterable

import numpy as np

NDIGITS: int
LINEAR: int
GAUSSIAN: int
ERF: int
COS: int
SINC: int
EXP: int
INTERP: int
LINEARCHIRP: int
EXPONENTIALCHIRP: int
HYPERBOLICCHIRP: int
COSH: int
SINH: int
DRAG: int
MOLLIFIER: int
D_GAUSSIAN: int


class PackedWaveform:
    def __init__(self, data: bytes | bytearray | memoryview = ...) -> None: ...
    @classmethod
    def from_bytes(cls, data: bytes | bytearray | memoryview) -> PackedWaveform: ...
    def to_bytes(self) -> bytes: ...
    def get_bounds(self) -> np.ndarray: ...
    def get_bound_ticks(self) -> np.ndarray: ...
    def shifted(self, time: float) -> PackedWaveform: ...
    def scaled(self, value: int | float | complex) -> PackedWaveform: ...
    def add(self, other: PackedWaveform) -> PackedWaveform: ...
    def mul(self, other: PackedWaveform) -> PackedWaveform: ...
    def power(self, n: int) -> PackedWaveform: ...
    def simplify(self, eps: float = ...) -> PackedWaveform: ...
    def filtered(self, low: float = ..., high: float = ...,
                 eps: float = ...) -> PackedWaveform: ...
    def derivative(self, order: int = ...) -> PackedWaveform: ...
    def evaluate(self, x: np.ndarray, lower: float = ...,
                 upper: float = ...) -> np.ndarray: ...
    def evaluate_shifted(self, x: np.ndarray, delay: float,
                         lower: float = ..., upper: float = ...) -> np.ndarray: ...
    def parts(self, x: np.ndarray, lower: float = ...,
              upper: float = ...) -> tuple[list, type]: ...
    def parts_shifted(self, x: np.ndarray, delay: float,
                      lower: float = ..., upper: float = ...) -> tuple[list, type]: ...


class PackedStack:
    @classmethod
    def from_bytes(cls, data: bytes | bytearray | memoryview) -> PackedStack: ...
    @classmethod
    def from_events(cls, events: Iterable[tuple[PackedWaveform, float,
                                                complex]]) -> PackedStack: ...
    def to_bytes(self) -> bytes: ...
    def events(self) -> tuple[tuple[PackedWaveform, float, complex], ...]: ...
    def evaluate(self, x: np.ndarray, offset: complex = ...,
                 shift: float = ...) -> np.ndarray: ...
    def simplified(self, shift: float = ..., offset: complex = ...,
                   eps: float = ...) -> PackedWaveform: ...
    def combined(self, other: PackedStack) -> PackedStack: ...
    def scaled(self, value: complex) -> PackedStack: ...


def constant(value: int | float | complex) -> PackedWaveform: ...
def basic(opcode: int, args: tuple = ..., shift: float = ...) -> PackedWaveform: ...
def piecewise(bounds: tuple, expressions: tuple) -> PackedWaveform: ...
def sum_cores(cores: Iterable[PackedWaveform]) -> PackedWaveform: ...
def set_time_resolution(value: float) -> None: ...
def get_time_resolution() -> float: ...
def quantize_time(value: float) -> float: ...
def registerBaseFunc(*args, **kwargs): ...
def registerDerivative(*args, **kwargs): ...
