from typing import Iterable

import numpy as np

LINEAR: int
GAUSSIAN: int
ERF: int
COS: int
SINC: int
EXP: int
INTERP: int
LINEARCHIRP: int
EXPONENTIALCHIRP: int
HYPERBOLICCHIRP: int
COSH: int
SINH: int
DRAG: int
MOLLIFIER: int
D_GAUSSIAN: int
DRAG_SIN: int
DRAG_SINX: int


def set_time_resolution(value: float) -> None: ...
def lock_time_resolution() -> None: ...
def get_time_resolution() -> float: ...
def quantize_time(value: float) -> float: ...
def time_to_tick(value: float) -> int: ...
def tick_to_time(tick: int) -> float: ...
def sample_clock(sample_rate: int | float) -> tuple[int, int]: ...
def sample_grid(start_tick: int, count: int, step_numerator: int,
                step_denominator: int = ...,
                index_offset: int = ...) -> np.ndarray: ...
def quantize_samples(values: np.ndarray, bits: int, full_scale: float = ...,
                     out: np.ndarray | None = ...) -> np.ndarray: ...
def place_template_quantized(out: np.ndarray, template: np.ndarray,
                             destinations: np.ndarray, scales: np.ndarray,
                             offset: float = ...,
                             full_scale: float = ...) -> np.ndarray: ...
def place_quantized_template(out: np.ndarray, template: np.ndarray,
                             destinations: np.ndarray) -> np.ndarray: ...
def accumulate_template(out: np.ndarray, template: np.ndarray,
                        destinations: np.ndarray,
                        scales: np.ndarray) -> np.ndarray: ...
def registerBaseFunc(*args, **kwargs): ...
def registerDerivative(*args, **kwargs): ...
TICKS_PER_SECOND: int
def set_c_ticks_per_second(value: int) -> None: ...
def get_c_ticks_per_second() -> int: ...

class CWaveformCore:
    @staticmethod
    def constant(value: float) -> CWaveformCore: ...
    @staticmethod
    def gaussian(width: float) -> CWaveformCore: ...
    @staticmethod
    def cos(angular_frequency: float, phase: float = ...) -> CWaveformCore: ...
    @staticmethod
    def sin(angular_frequency: float, phase: float = ...) -> CWaveformCore: ...
    @staticmethod
    def square(width: float) -> CWaveformCore: ...
    @staticmethod
    def builtin(opcode: int, parameters=(), shift: int = ...) -> CWaveformCore: ...
    @classmethod
    def from_bytes(cls, data: bytes | bytearray | memoryview) -> CWaveformCore: ...
    def to_bytes(self) -> bytes: ...
    def add_affine(self, other: CWaveformCore, left_delay: int = ...,
                   left_scale: float = ..., right_delay: int = ...,
                   right_scale: float = ...) -> CWaveformCore: ...
    def mul_affine(self, other: CWaveformCore, left_delay: int = ...,
                   left_scale: float = ..., right_delay: int = ...,
                   right_scale: float = ...) -> CWaveformCore: ...
    def materialize(self, delay: int = ..., scale: float = ...) -> CWaveformCore: ...
    def window(self, lower: int, upper: int) -> CWaveformCore: ...
    def power(self, exponent: int) -> CWaveformCore: ...
    def derivative(self, order: int = ...) -> CWaveformCore: ...
    def filtered(self, low: float = ..., high: float = ...,
                 epsilon: float = ...) -> CWaveformCore: ...
    def simplify(self, epsilon: float = ...) -> CWaveformCore: ...
    def evaluate(self, positions: np.ndarray, delay: int = ...,
                 scale: float = ..., lower: float = ...,
                 upper: float = ..., out: np.ndarray | None = ...) -> np.ndarray: ...
    def sample(self, start_tick: int, count: int, step_numerator: int,
               step_denominator: int = ..., delay: int = ...,
               scale: float = ..., lower: float = ..., upper: float = ...,
               bits: int = ..., full_scale: float = ...,
               out: np.ndarray | None = ...) -> np.ndarray: ...
    lower_tick: int
    upper_tick: int
    node_count: int
    hash64: int

class CWaveformStackCore:
    @classmethod
    def from_events(cls, templates: Iterable[CWaveformCore], template_ids,
                    delays, scales) -> CWaveformStackCore: ...
    @classmethod
    def from_bytes(cls, data: bytes | bytearray | memoryview) -> CWaveformStackCore: ...
    def to_bytes(self) -> bytes: ...
    def evaluate(self, positions: np.ndarray, shift: int = ...,
                 offset: float = ..., out: np.ndarray | None = ...) -> np.ndarray: ...
    def sample(self, start_tick: int, count: int, step_numerator: int,
               step_denominator: int = ..., shift: int = ...,
               offset: float = ..., bits: int = ...,
               full_scale: float = ...,
               out: np.ndarray | None = ...) -> np.ndarray: ...
    def prepare_sample(self, start_tick: int, count: int,
                       step_numerator: int, step_denominator: int = ...,
                       shift: int = ...) -> CWaveformSamplePlan | None: ...
    def simplify(self, shift: int = ..., offset: float = ...) -> CWaveformCore: ...
    def materialize(self, shift: int = ...,
                    offset: float = ...) -> CWaveformStackCore: ...
    def combine(self, other: CWaveformStackCore, left_shift: int = ...,
                right_shift: int = ...) -> CWaveformStackCore: ...
    def append(self, wave: CWaveformCore, global_shift: int = ...,
               wave_delay: int = ...,
               wave_scale: float = ...) -> CWaveformStackCore: ...
    def scaled(self, scale: float) -> CWaveformStackCore: ...
    event_count: int
    template_count: int
    hash64: int

class CWaveformSamplePlan:
    def sample(self, offset: float = ..., bits: int = ...,
               full_scale: float = ...,
               out: np.ndarray | None = ...) -> np.ndarray: ...
    count: int
    group_count: int
    non_overlapping: bool

def c_format_description() -> str: ...
