from typing import Iterable

import numpy as np

NDIGITS: int
LINEAR: int
GAUSSIAN: int
ERF: int
COS: int
SINC: int
EXP: int
INTERP: int
LINEARCHIRP: int
EXPONENTIALCHIRP: int
HYPERBOLICCHIRP: int
COSH: int
SINH: int
DRAG: int
MOLLIFIER: int
D_GAUSSIAN: int
DRAG_SIN: int
DRAG_SINX: int


class PackedWaveform:
    def __init__(self, data: bytes | bytearray | memoryview = ...) -> None: ...
    @classmethod
    def from_bytes(cls, data: bytes | bytearray | memoryview) -> PackedWaveform: ...
    def to_bytes(self) -> bytes: ...
    def get_bounds(self) -> np.ndarray: ...
    def get_bound_ticks(self) -> np.ndarray: ...
    def support_ticks(self) -> tuple[int, int]: ...
    def shifted(self, time: float) -> PackedWaveform: ...
    def scaled(self, value: int | float) -> PackedWaveform: ...
    def add(self, other: PackedWaveform) -> PackedWaveform: ...
    def add_affine(self, other: PackedWaveform, left_delay: float = ...,
                   left_scale: float = ..., right_delay: float = ...,
                   right_scale: float = ...) -> PackedWaveform: ...
    def mul(self, other: PackedWaveform) -> PackedWaveform: ...
    def mul_affine(self, other: PackedWaveform, left_delay: float = ...,
                   right_delay: float = ...) -> PackedWaveform: ...
    def power(self, n: int) -> PackedWaveform: ...
    def simplify(self, eps: float = ...) -> PackedWaveform: ...
    def filtered(self, low: float = ..., high: float = ...,
                 eps: float = ...) -> PackedWaveform: ...
    def derivative(self, order: int = ...) -> PackedWaveform: ...
    def evaluate(self, x: np.ndarray, lower: float = ...,
                 upper: float = ...) -> np.ndarray: ...
    def evaluate_shifted(self, x: np.ndarray, delay: float,
                         lower: float = ..., upper: float = ...) -> np.ndarray: ...
    def parts(self, x: np.ndarray, lower: float = ...,
              upper: float = ...) -> tuple[list, type]: ...
    def parts_shifted(self, x: np.ndarray, delay: float,
                      lower: float = ..., upper: float = ...) -> tuple[list, type]: ...


class PackedStack:
    @classmethod
    def from_bytes(cls, data: bytes | bytearray | memoryview) -> PackedStack: ...
    @classmethod
    def from_events(cls, events: Iterable[tuple[PackedWaveform, float,
                                                float]]) -> PackedStack: ...
    def to_bytes(self) -> bytes: ...
    def events(self) -> tuple[tuple[PackedWaveform, float, float], ...]: ...
    def evaluate(self, x: np.ndarray, offset: float = ...,
                 shift: float = ...) -> np.ndarray: ...
    def simplified(self, shift: float = ..., offset: float = ...,
                   eps: float = ...) -> PackedWaveform: ...
    def combined(self, other: PackedStack) -> PackedStack: ...
    def scaled(self, value: float) -> PackedStack: ...


def constant(value: int | float) -> PackedWaveform: ...
def basic(opcode: int, args: tuple = ..., shift: float = ...) -> PackedWaveform: ...
def basic_expression(opcode: int, args: tuple = ..., shift: float = ...) -> tuple: ...
def affine_expression(opcode: int, args: tuple = ..., shift: float = ...,
                      scale: float = ..., offset: float = ...) -> tuple: ...
def piecewise(bounds: tuple, expressions: tuple) -> PackedWaveform: ...
def piecewise_canonical(bounds: tuple, expressions: tuple) -> PackedWaveform: ...
def sum_cores(cores: Iterable[PackedWaveform]) -> PackedWaveform: ...
def set_time_resolution(value: float) -> None: ...
def get_time_resolution() -> float: ...
def quantize_time(value: float) -> float: ...
def time_to_tick(value: float) -> int: ...
def tick_to_time(tick: int) -> float: ...
def sample_clock(sample_rate: int | float) -> tuple[int, int]: ...
def sample_grid(start_tick: int, count: int, step_numerator: int,
                step_denominator: int = ...,
                index_offset: int = ...) -> np.ndarray: ...
def quantize_samples(values: np.ndarray, bits: int, full_scale: float = ...,
                     out: np.ndarray | None = ...) -> np.ndarray: ...
def place_template_quantized(out: np.ndarray, template: np.ndarray,
                             destinations: np.ndarray, scales: np.ndarray,
                             offset: float = ...,
                             full_scale: float = ...) -> np.ndarray: ...
def place_quantized_template(out: np.ndarray, template: np.ndarray,
                             destinations: np.ndarray) -> np.ndarray: ...
def accumulate_template(out: np.ndarray, template: np.ndarray,
                        destinations: np.ndarray,
                        scales: np.ndarray) -> np.ndarray: ...
def registerBaseFunc(*args, **kwargs): ...
def registerDerivative(*args, **kwargs): ...
TICKS_PER_SECOND: int

class NativeCore:
    @staticmethod
    def constant(value: float) -> NativeCore: ...
    @staticmethod
    def gaussian(width: float) -> NativeCore: ...
    @staticmethod
    def cos(angular_frequency: float, phase: float = ...) -> NativeCore: ...
    @staticmethod
    def sin(angular_frequency: float, phase: float = ...) -> NativeCore: ...
    @staticmethod
    def square(width: float) -> NativeCore: ...
    @classmethod
    def from_bytes(cls, data: bytes | bytearray | memoryview) -> NativeCore: ...
    def to_bytes(self) -> bytes: ...
    def add_affine(self, other: NativeCore, left_delay: int = ...,
                   left_scale: float = ..., right_delay: int = ...,
                   right_scale: float = ...) -> NativeCore: ...
    def mul_affine(self, other: NativeCore, left_delay: int = ...,
                   left_scale: float = ..., right_delay: int = ...,
                   right_scale: float = ...) -> NativeCore: ...
    def materialize(self, delay: int = ..., scale: float = ...) -> NativeCore: ...
    def evaluate(self, positions: np.ndarray, delay: int = ...,
                 scale: float = ..., lower: float = ...,
                 upper: float = ..., out: np.ndarray | None = ...) -> np.ndarray: ...
    def sample(self, start_tick: int, count: int, step_numerator: int,
               step_denominator: int = ..., delay: int = ...,
               scale: float = ..., lower: float = ..., upper: float = ...,
               bits: int = ..., full_scale: float = ...,
               out: np.ndarray | None = ...) -> np.ndarray: ...
    lower_tick: int
    upper_tick: int
    node_count: int
    hash64: int

class NativeStackCore:
    @classmethod
    def from_events(cls, templates: Iterable[NativeCore], template_ids,
                    delays, scales) -> NativeStackCore: ...
    @classmethod
    def from_bytes(cls, data: bytes | bytearray | memoryview) -> NativeStackCore: ...
    def to_bytes(self) -> bytes: ...
    def evaluate(self, positions: np.ndarray, shift: int = ...,
                 offset: float = ..., out: np.ndarray | None = ...) -> np.ndarray: ...
    def sample(self, start_tick: int, count: int, step_numerator: int,
               step_denominator: int = ..., shift: int = ...,
               offset: float = ..., bits: int = ...,
               full_scale: float = ...,
               out: np.ndarray | None = ...) -> np.ndarray: ...
    def prepare_sample(self, start_tick: int, count: int,
                       step_numerator: int, step_denominator: int = ...,
                       shift: int = ...) -> NativeSamplePlan | None: ...
    def simplify(self, shift: int = ..., offset: float = ...) -> NativeCore: ...
    def materialize(self, shift: int = ...,
                    offset: float = ...) -> NativeStackCore: ...
    event_count: int
    template_count: int
    hash64: int

class NativeSamplePlan:
    def sample(self, offset: float = ..., bits: int = ...,
               full_scale: float = ...,
               out: np.ndarray | None = ...) -> np.ndarray: ...
    count: int
    group_count: int
    non_overlapping: bool

def native_format_description() -> str: ...
