language: python
install:
- pip3 install pytest-cov
- pip3 install coveralls
- pip3 install -e .
script:
- pytest --cov=qulab --verbose
after_success:
- coveralls
deploy:
  provider: pypi
  user: __token__
  password:
    secure: ORAbWpR9c1Bv2xmSGLb9MQ/zy5YIK+U3DiYOXzhrnEQc+J2GY3apSYay8V3JrQRXWVYwceJoouNvQFK3pqMznDDXGzLZT0z/cjYhApi2Dv4Z1qYU1K/8GseRKkIsR9+zmzUadx55DctGsb1fOZn7HRYiujYNHp919PZ/1gWv8ilUadNuB42E+OXN9ldDLYv/sOGeeGv5c79O02Qbek8qFL0aZxg99D3nHk94w14WJWyP9unVab9ivD/1px/Zxq6McK0O9ieWBKz4Cj43raIJygKSlZ/gw6fb3+YXLnJD0F2hU4aybl4R4KMjYMVpBuSI/uKWKUBIqLoOKJOUGdbePoHrhsvrvnRMLN+45zDnygG/yArISyJ+IBwtCy+Py5dL/Rwl+0q+QEZ+xeZtXfitNT9ZJnShCDIQbenJ/W5un+ZUe05QSqMxw7Igcqi9lOmo0VBYag4GSNE3f5mKnCFw+Ud2Nr22mr17dkrKuKquwRIdfQytuozO5QcVKgqd9Mn3kfspPJFkyJcw16dLPSYHZzqcFSV4KrB8ILyjiAvny1E0Au/X14DV3oZISWMNhoNgP9R/tYQnS0zsHoOEIOkDbNNS3FlKu55Fp/o/QoSm/NDGbtvYSRksFdN57SFfCXsudW4/X4pI/GdWZjEjzWpARQllH5dxWTLQJqsEv1UC42E=
  on:
    branch: master
    tags: true
    condition: "$DEPLOY = yes"
  skip_existing: true
  skip_cleanup: true
  distributions: sdist bdist_wheel
