language: python
install:
- pip3 install pytest-cov
- pip3 install coveralls
- pip3 install -e .
script:
- pytest --cov=qulab --verbose
after_success:
- coveralls
deploy:
  provider: pypi
  user: __token__
  password:
    secure: ecXV8F0ihivAXlFygThQ35zK0JM+5SnUx1YqljzGDECZMK2mEehGKnTPk14YBFirvghl3cIM9e6Ct8xaU5pj758asQCmZgt0J3TBaJdPNPOfy6nZpj1nb+lBdjLMUoIw18P4hpzkrt9u4WVtCjC52c/Ymq0OnTpCygcVNCwC0sJdPkytNiKQzoA6bK5W8bva44tUYVA7rek07HW09jJ8mE8PyYQZKY4NfN7MSiDm++2BVgJCA7BCGkMS87a+UDF9Eq6LR7E7Wn9RktsU5yzEtmbnM2cz52faONIZIQCb2wwL7SiakfbXI4kZH9aJx1/Q6zs35+tqGUUXTMRqqOQMiUrnL3IPb8olloSvpaxbhZuvLOK7wVUEphtpvfhCVW/cK/e6Z4EFY1PCmMONprJfubB5IwiCo4DfQrpCDdj0mSdGoRlhumRnoTVEzPB4B0Eh/z4I+gTlFyFXLCPuilag6UcHKbEAuz0Mf09eyF+Jz4niFoyGXut3vFuUsHZfQLEBsPnqi3F+kxXl7qeTkJJTHPFz1GFvZ4TvWEplKUEU0fV25vOh4PcMQ5GXH0HPF9UqXqZmo9xy9f3qfEaSwjQ9MEKpB+TpZuCwJ0BAkdFckxafOm3vW9NirJ0WZCrKJPGjN2I+dOeG0pTCeCsZoV4lQnG8lJWdfGU2exFFhAydptA=
  on:
    branch: master
    tags: true
    condition: "$DEPLOY = yes"
  skip_existing: true
  skip_cleanup: true
  distributions: sdist bdist_wheel
